name: Deploy Angular App
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: node version
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm install
      - name: Lint application
        run: npm run lint
