name: Deploy Angular App
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./my-book-shelf
        run: npm ci
      - name: Lint application
        run: npm run lint
