name: Deploy Angular App
run-name: ${{ github.actor }} is pushed updates
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Go to root folder
        working-directory: ./my-book-shelf
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
