name: Lint and testing my-book-shelf app
on: [push]
jobs:
  lint-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: node version
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
      - name: Install dependencies
        working-directory: ./my-book-shelf
        run: npm ci
      - name: Lint application
        working-directory: ./my-book-shelf
        run: npm run lint
      - name: Test application
        working-directory: ./my-book-shelf
        run: npm run ci-test
